[workspace]
authors = ["Adrian <adrian.veen@gmail.com>"]
channels = ["conda-forge"]
name = "testpad"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]

[environments]
dev = { features = ["dev"], no-default-feature = true }
release = { features = ["release"], no-default-feature = true }

[feature.dev]
channels = ["conda-forge", "main", "r", "msys2"]

[feature.dev.dependencies]
_openmp_mutex = { version = "==4.5", build = "2_gnu" }
altgraph = { version = "==0.17.4", build = "pyhd8ed1ab_1" }
brotli = { version = "==1.1.0", build = "h2466b09_3" }
brotli-bin = { version = "==1.1.0", build = "h2466b09_3" }
bzip2 = { version = "==1.0.8", build = "h2466b09_7" }
ca-certificates = { version = "==2025.8.3", build = "h4c7d964_0" }
cached-property = { version = "==1.5.2", build = "hd8ed1ab_1" }
cached_property = { version = "==1.5.2", build = "pyha770c72_1" }
cairo = { version = "==1.18.4", build = "h5782bbf_0" }
contourpy = { version = "==1.3.3", build = "py312hf90b1b7_1" }
cycler = { version = "==0.12.1", build = "pyhd8ed1ab_1" }
double-conversion = { version = "==3.3.1", build = "he0c23c2_0" }
font-ttf-dejavu-sans-mono = { version = "==2.37", build = "hab24e00_0" }
font-ttf-inconsolata = { version = "==3.0", build = "h77eed37_0" }
font-ttf-source-code-pro = { version = "==2.38", build = "h77eed37_0" }
font-ttf-ubuntu = { version = "==0.83", build = "h77eed37_3" }
fontconfig = { version = "==2.15.0", build = "h765892d_1" }
fonts-conda-ecosystem = { version = "==1", build = "0" }
fonts-conda-forge = { version = "==1", build = "0" }
fonttools = { version = "==4.59.2", build = "py312h05f76fc_0" }
freetype = { version = "==2.13.3", build = "h57928b3_1" }
future = { version = "==1.0.0", build = "pyhd8ed1ab_2" }
graphite2 = { version = "==1.3.14", build = "hac47afa_2" }
h5py = { version = "==3.14.0", build = "nompi_py312h6cc2a29_100" }
harfbuzz = { version = "==11.2.1", build = "h8796e6f_0" }
hdf5 = { version = "==1.14.6", build = "nompi_he30205f_103" }
icu = { version = "==75.1", build = "he0c23c2_0" }
importlib-metadata = { version = "==8.7.0", build = "pyhe01879c_1" }
kiwisolver = { version = "==1.4.9", build = "py312h78d62e6_0" }
krb5 = { version = "==1.21.3", build = "hdf4eb48_0" }
lcms2 = { version = "==2.17", build = "hbcf6048_0" }
lerc = { version = "==4.0.0", build = "h6470a55_1" }
libaec = { version = "==1.1.4", build = "h20038f6_0" }
libblas = { version = "==3.9.0", build = "34_h5709861_mkl" }
libbrotlicommon = { version = "==1.1.0", build = "h2466b09_3" }
libbrotlidec = { version = "==1.1.0", build = "h2466b09_3" }
libbrotlienc = { version = "==1.1.0", build = "h2466b09_3" }
libcblas = { version = "==3.9.0", build = "34_h2a3cdd5_mkl" }
libclang13 = { version = "==20.1.8", build = "default_hadf22e1_0" }
libcurl = { version = "==8.14.1", build = "h88aaa65_0" }
libdeflate = { version = "==1.24", build = "h76ddb4d_0" }
libexpat = { version = "==2.7.1", build = "hac47afa_0" }
libffi = { version = "==3.4.6", build = "h537db12_1" }
libfreetype = { version = "==2.13.3", build = "h57928b3_1" }
libfreetype6 = { version = "==2.13.3", build = "h0b5ce68_1" }
libgcc = { version = "==15.1.0", build = "h1383e82_4" }
libglib = { version = "==2.84.1", build = "h7025463_0" }
libgomp = { version = "==15.1.0", build = "h1383e82_4" }
libhwloc = { version = "==2.12.1", build = "default_h88281d1_1000" }
libiconv = { version = "==1.18", build = "hc1393d2_2" }
libintl = { version = "==0.22.5", build = "h5728263_3" }
libjpeg-turbo = { version = "==3.1.0", build = "h2466b09_0" }
liblapack = { version = "==3.9.0", build = "34_hf9ab0e9_mkl" }
liblzma = { version = "==5.8.1", build = "h2466b09_2" }
libpng = { version = "==1.6.50", build = "h7351971_1" }
libsqlite = { version = "==3.50.4", build = "hf5d6505_0" }
libssh2 = { version = "==1.11.1", build = "h9aa295b_0" }
libtiff = { version = "==4.7.0", build = "h550210a_6" }
libwebp-base = { version = "==1.6.0", build = "h4d5522a_0" }
libwinpthread = { version = "==12.0.0.r4.gg4f2fc60ca", build = "h57928b3_9" }
libxcb = { version = "==1.17.0", build = "h0e4246c_0" }
libxml2 = { version = "==2.13.8", build = "h741aa76_1" }
libxslt = { version = "==1.1.43", build = "h25c3957_0" }
libzlib = { version = "==1.3.1", build = "h2466b09_2" }
llvm-openmp = { version = "==20.1.8", build = "hfa2b4ca_2" }
matplotlib = { version = "==3.10.5", build = "py312h2e8e312_0" }
matplotlib-base = { version = "==3.10.5", build = "py312h0ebf65c_0" }
mkl = { version = "==2024.2.2", build = "h57928b3_16" }
munkres = { version = "==1.1.4", build = "pyhd8ed1ab_1" }
numpy = { version = "==2.3.2", build = "py312ha72d056_2" }
openjpeg = { version = "==2.5.3", build = "h24db6dd_1" }
openssl = { version = "==3.5.2", build = "h725018a_0" }
packaging = { version = "==25.0", build = "pyh29332c3_1" }
pandas = { version = "==2.3.2", build = "py312hc128f0a_0" }
pcre2 = { version = "==10.44", build = "h99c9b8b_2" }
pefile = { version = "==2023.2.7", build = "pyhd8ed1ab_0" }
pillow = { version = "==11.3.0", build = "py312hfb502af_0" }
pip = { version = "==25.2", build = "pyh8b19718_0" }
pixman = { version = "==0.46.4", build = "h5112557_1" }
pthread-stubs = { version = "==0.4", build = "h0e40799_1002" }
pyinstaller = { version = "==6.15.0", build = "py312hf4647a0_0" }
pyinstaller-hooks-contrib = { version = "==2025.8", build = "pyhd8ed1ab_0" }
pyparsing = { version = "==3.2.3", build = "pyhe01879c_2" }
pyside6 = { version = "==6.7.2", build = "py312h2ee7485_4" }
python = { version = "==3.12.11", build = "h3f84c4b_0_cpython" }
python-dateutil = { version = "==2.9.0.post0", build = "pyhe01879c_2" }
python-tzdata = { version = "==2025.2", build = "pyhd8ed1ab_0" }
python_abi = { version = "==3.12", build = "8_cp312" }
pytz = { version = "==2025.2", build = "pyhd8ed1ab_0" }
pywin32 = { version = "==311", build = "py312h829343e_0" }
pywin32-ctypes = { version = "==0.2.3", build = "py312h2e8e312_2" }
pyyaml = { version = "==6.0.2", build = "py312h31fea79_2" }
qhull = { version = "==2020.2", build = "hc790b64_5" }
qt6-main = { version = "==6.7.2", build = "h2fedb45_5" }
scipy = { version = "==1.16.1", build = "py312hb2f131f_0" }
setuptools = { version = "==80.9.0", build = "pyhff2d567_0" }
six = { version = "==1.17.0", build = "pyhe01879c_1" }
tbb = { version = "==2021.13.0", build = "h18a62a1_3" }
tk = { version = "==8.6.13", build = "h2c6b04d_2" }
tornado = { version = "==6.5.2", build = "py312he06e257_0" }
tzdata = { version = "==2025b", build = "h78e105d_0" }
ucrt = { version = "==10.0.26100.0", build = "h57928b3_0" }
unicodedata2 = { version = "==16.0.0", build = "py312h4389bb4_0" }
vc = { version = "==14.3", build = "h41ae7f8_31" }
vc14_runtime = { version = "==14.44.35208", build = "h818238b_31" }
vcomp14 = { version = "==14.44.35208", build = "h818238b_31" }
wheel = { version = "==0.45.1", build = "pyhd8ed1ab_1" }
xorg-libxau = { version = "==1.0.12", build = "h0e40799_0" }
xorg-libxdmcp = { version = "==1.1.5", build = "h0e40799_0" }
yaml = { version = "==0.2.5", build = "h6a83c73_3" }
zipp = { version = "==3.23.0", build = "pyhd8ed1ab_0" }
zstd = { version = "==1.5.7", build = "hbeecb71_2" }

[feature.release]
channels = ["conda-forge", "main", "r", "msys2"]

[feature.release.dependencies]
_openmp_mutex = { version = "==4.5", build = "2_gnu" }
altgraph = { version = "==0.17.4", build = "pyhd8ed1ab_1" }
brotli = { version = "==1.1.0", build = "h2466b09_3" }
brotli-bin = { version = "==1.1.0", build = "h2466b09_3" }
bzip2 = { version = "==1.0.8", build = "h2466b09_7" }
ca-certificates = { version = "==2025.8.3", build = "h4c7d964_0" }
cached-property = { version = "==1.5.2", build = "hd8ed1ab_1" }
cached_property = { version = "==1.5.2", build = "pyha770c72_1" }
cairo = { version = "==1.18.4", build = "h5782bbf_0" }
contourpy = { version = "==1.3.3", build = "py312hf90b1b7_1" }
cycler = { version = "==0.12.1", build = "pyhd8ed1ab_1" }
double-conversion = { version = "==3.3.1", build = "he0c23c2_0" }
font-ttf-dejavu-sans-mono = { version = "==2.37", build = "hab24e00_0" }
font-ttf-inconsolata = { version = "==3.0", build = "h77eed37_0" }
font-ttf-source-code-pro = { version = "==2.38", build = "h77eed37_0" }
font-ttf-ubuntu = { version = "==0.83", build = "h77eed37_3" }
fontconfig = { version = "==2.15.0", build = "h765892d_1" }
fonts-conda-ecosystem = { version = "==1", build = "0" }
fonts-conda-forge = { version = "==1", build = "0" }
fonttools = { version = "==4.59.2", build = "py312h05f76fc_0" }
freetype = { version = "==2.13.3", build = "h57928b3_1" }
future = { version = "==1.0.0", build = "pyhd8ed1ab_2" }
graphite2 = { version = "==1.3.14", build = "hac47afa_2" }
h5py = { version = "==3.14.0", build = "nompi_py312h6cc2a29_100" }
harfbuzz = { version = "==11.2.1", build = "h8796e6f_0" }
hdf5 = { version = "==1.14.6", build = "nompi_he30205f_103" }
icu = { version = "==75.1", build = "he0c23c2_0" }
importlib-metadata = { version = "==8.7.0", build = "pyhe01879c_1" }
kiwisolver = { version = "==1.4.9", build = "py312h78d62e6_0" }
krb5 = { version = "==1.21.3", build = "hdf4eb48_0" }
lcms2 = { version = "==2.17", build = "hbcf6048_0" }
lerc = { version = "==4.0.0", build = "h6470a55_1" }
libaec = { version = "==1.1.4", build = "h20038f6_0" }
libblas = { version = "==3.9.0", build = "34_h5709861_mkl" }
libbrotlicommon = { version = "==1.1.0", build = "h2466b09_3" }
libbrotlidec = { version = "==1.1.0", build = "h2466b09_3" }
libbrotlienc = { version = "==1.1.0", build = "h2466b09_3" }
libcblas = { version = "==3.9.0", build = "34_h2a3cdd5_mkl" }
libclang13 = { version = "==20.1.8", build = "default_hadf22e1_0" }
libcurl = { version = "==8.14.1", build = "h88aaa65_0" }
libdeflate = { version = "==1.24", build = "h76ddb4d_0" }
libexpat = { version = "==2.7.1", build = "hac47afa_0" }
libffi = { version = "==3.4.6", build = "h537db12_1" }
libfreetype = { version = "==2.13.3", build = "h57928b3_1" }
libfreetype6 = { version = "==2.13.3", build = "h0b5ce68_1" }
libgcc = { version = "==15.1.0", build = "h1383e82_4" }
libglib = { version = "==2.84.1", build = "h7025463_0" }
libgomp = { version = "==15.1.0", build = "h1383e82_4" }
libhwloc = { version = "==2.12.1", build = "default_h88281d1_1000" }
libiconv = { version = "==1.18", build = "hc1393d2_2" }
libintl = { version = "==0.22.5", build = "h5728263_3" }
libjpeg-turbo = { version = "==3.1.0", build = "h2466b09_0" }
liblapack = { version = "==3.9.0", build = "34_hf9ab0e9_mkl" }
liblzma = { version = "==5.8.1", build = "h2466b09_2" }
libpng = { version = "==1.6.50", build = "h7351971_1" }
libsqlite = { version = "==3.50.4", build = "hf5d6505_0" }
libssh2 = { version = "==1.11.1", build = "h9aa295b_0" }
libtiff = { version = "==4.7.0", build = "h550210a_6" }
libwebp-base = { version = "==1.6.0", build = "h4d5522a_0" }
libwinpthread = { version = "==12.0.0.r4.gg4f2fc60ca", build = "h57928b3_9" }
libxcb = { version = "==1.17.0", build = "h0e4246c_0" }
libxml2 = { version = "==2.13.8", build = "h741aa76_1" }
libxslt = { version = "==1.1.43", build = "h25c3957_0" }
libzlib = { version = "==1.3.1", build = "h2466b09_2" }
llvm-openmp = { version = "==20.1.8", build = "hfa2b4ca_2" }
matplotlib = { version = "==3.10.5", build = "py312h2e8e312_0" }
matplotlib-base = { version = "==3.10.5", build = "py312h0ebf65c_0" }
mkl = { version = "==2024.2.2", build = "h57928b3_16" }
munkres = { version = "==1.1.4", build = "pyhd8ed1ab_1" }
numpy = { version = "==2.3.2", build = "py312ha72d056_2" }
openjpeg = { version = "==2.5.3", build = "h24db6dd_1" }
openssl = { version = "==3.5.2", build = "h725018a_0" }
packaging = { version = "==25.0", build = "pyh29332c3_1" }
pandas = { version = "==2.3.2", build = "py312hc128f0a_0" }
pcre2 = { version = "==10.44", build = "h99c9b8b_2" }
pefile = { version = "==2023.2.7", build = "pyhd8ed1ab_0" }
pillow = { version = "==11.3.0", build = "py312hfb502af_0" }
pip = { version = "==25.2", build = "pyh8b19718_0" }
pixman = { version = "==0.46.4", build = "h5112557_1" }
pthread-stubs = { version = "==0.4", build = "h0e40799_1002" }
pyinstaller = { version = "==6.15.0", build = "py312hf4647a0_0" }
pyinstaller-hooks-contrib = { version = "==2025.8", build = "pyhd8ed1ab_0" }
pyparsing = { version = "==3.2.3", build = "pyhe01879c_2" }
pyside6 = { version = "==6.7.2", build = "py312h2ee7485_4" }
python = { version = "==3.12.11", build = "h3f84c4b_0_cpython" }
python-dateutil = { version = "==2.9.0.post0", build = "pyhe01879c_2" }
python-tzdata = { version = "==2025.2", build = "pyhd8ed1ab_0" }
python_abi = { version = "==3.12", build = "8_cp312" }
pytz = { version = "==2025.2", build = "pyhd8ed1ab_0" }
pywin32 = { version = "==311", build = "py312h829343e_0" }
pywin32-ctypes = { version = "==0.2.3", build = "py312h2e8e312_2" }
pyyaml = { version = "==6.0.2", build = "py312h31fea79_2" }
qhull = { version = "==2020.2", build = "hc790b64_5" }
qt6-main = { version = "==6.7.2", build = "h2fedb45_5" }
scipy = { version = "==1.16.1", build = "py312hb2f131f_0" }
setuptools = { version = "==80.9.0", build = "pyhff2d567_0" }
six = { version = "==1.17.0", build = "pyhe01879c_1" }
tbb = { version = "==2021.13.0", build = "h18a62a1_3" }
tk = { version = "==8.6.13", build = "h2c6b04d_2" }
tornado = { version = "==6.5.2", build = "py312he06e257_0" }
tzdata = { version = "==2025b", build = "h78e105d_0" }
ucrt = { version = "==10.0.26100.0", build = "h57928b3_0" }
unicodedata2 = { version = "==16.0.0", build = "py312h4389bb4_0" }
vc = { version = "==14.3", build = "h41ae7f8_31" }
vc14_runtime = { version = "==14.44.35208", build = "h818238b_31" }
vcomp14 = { version = "==14.44.35208", build = "h818238b_31" }
wheel = { version = "==0.45.1", build = "pyhd8ed1ab_1" }
xorg-libxau = { version = "==1.0.12", build = "h0e40799_0" }
xorg-libxdmcp = { version = "==1.1.5", build = "h0e40799_0" }
yaml = { version = "==0.2.5", build = "h6a83c73_3" }
zipp = { version = "==3.23.0", build = "pyhd8ed1ab_0" }
zstd = { version = "==1.5.7", build = "hbeecb71_2" }
