name: testpad-release
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - altgraph=0.17.4=pyhd8ed1ab_1
  - brotli=1.1.0=h2466b09_3
  - brotli-bin=1.1.0=h2466b09_3
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.8.3=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h5782bbf_0
  - contourpy=1.3.3=py312hf90b1b7_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - double-conversion=3.3.1=he0c23c2_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.2=py312h05f76fc_0
  - freetype=2.13.3=h57928b3_1
  - future=1.0.0=pyhd8ed1ab_2
  - graphite2=1.3.14=hac47afa_2
  - h5py=3.14.0=nompi_py312h6cc2a29_100
  - harfbuzz=11.2.1=h8796e6f_0
  - hdf5=1.14.6=nompi_he30205f_103
  - icu=75.1=he0c23c2_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - kiwisolver=1.4.9=py312h78d62e6_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libaec=1.1.4=h20038f6_0
  - libblas=3.9.0=34_h5709861_mkl
  - libbrotlicommon=1.1.0=h2466b09_3
  - libbrotlidec=1.1.0=h2466b09_3
  - libbrotlienc=1.1.0=h2466b09_3
  - libcblas=3.9.0=34_h2a3cdd5_mkl
  - libclang13=20.1.8=default_hadf22e1_0
  - libcurl=8.14.1=h88aaa65_0
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libgcc=15.1.0=h1383e82_4
  - libglib=2.84.1=h7025463_0
  - libgomp=15.1.0=h1383e82_4
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=34_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libpng=1.6.50=h7351971_1
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.0=h550210a_6
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h741aa76_1
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=20.1.8=hfa2b4ca_2
  - matplotlib=3.10.5=py312h2e8e312_0
  - matplotlib-base=3.10.5=py312h0ebf65c_0
  - mkl=2024.2.2=h57928b3_16
  - munkres=1.1.4=pyhd8ed1ab_1
  - numpy=2.3.2=py312ha72d056_2
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.5.2=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py312hc128f0a_0
  - pcre2=10.44=h99c9b8b_2
  - pefile=2023.2.7=pyhd8ed1ab_0
  - pillow=11.3.0=py312hfb502af_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - pthread-stubs=0.4=h0e40799_1002
  - pyinstaller=6.15.0=py312hf4647a0_0
  - pyinstaller-hooks-contrib=2025.8=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pyside6=6.7.2=py312h2ee7485_4
  - python=3.12.11=h3f84c4b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py312h829343e_0
  - pywin32-ctypes=0.2.3=py312h2e8e312_2
  - pyyaml=6.0.2=py312h31fea79_2
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.7.2=h2fedb45_5
  - scipy=1.16.1=py312hb2f131f_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - tbb=2021.13.0=h18a62a1_3
  - tk=8.6.13=h2c6b04d_2
  - tornado=6.5.2=py312he06e257_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=16.0.0=py312h4389bb4_0
  - vc=14.3=h41ae7f8_31
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - yaml=0.2.5=h6a83c73_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=hbeecb71_2
prefix: C:\ProgramData\anaconda3\envs\testpad-release
